### PR TITLE
issue-801 : fixed error handling

### LINKED ISSUE #801: /v1/ltp-update is recorded in EATL twice if the response is 500
If the /v1/ltp-update is not successful and if the responseCode is 500 , then , the result is logging in both server and the client side resulting in two entries in the EATL application , 

example :

{
    "x-correlator": "590e8400-e11b-11d4-a716-446655440817",
    "trace-indicator": "1.2",
    "user": "User Name",
    "originator": "AdministratorAdministration",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 500
  },
  {
    "x-correlator": "590e8400-e11b-11d4-a716-446655440817",
    "trace-indicator": "1.2",
    "user": "User Name",
    "originator": "AdministratorAdministration",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 500,
    "timestamp": "2023-07-08T06:21:02+00:00",
    "stringified-body": "{\"uuid\":\"aa-2-0-1-http-c-ro-2-0-1-000\",\"ltp-direction\":\"core-model-1-4:TERMINATION_DIRECTION_SINK\",\"client-ltp\":[\"aa-2-0-1-op-c-bm-ro-2-0-1-000\",\"aa-2-0-1-op-c-bm-ro-2-0-1-001\",\"aa-2-0-1-op-c-bm-ro-2-0-1-002\",\"aa-2-0-1-op-c-bm-ro-2-0-1-003\",\"aa-2-0-1-op-c-im-ro-2-0-1-000\",\"aa-2-0-1-op-c-im-ro-2-0-1-001\",\"aa-2-0-1-op-c-im-ro-2-0-1-002\",\"aa-2-0-1-op-c-im-ro-2-0-1-004\"],\"server-ltp\":[\"aa-2-0-1-tcp-c-ro-2-0-1-000\"],\"layer-protocol\":[{\"local-id\":\"0\",\"layer-protocol-name\":\"http-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER\",\"http-client-interface-1-0:http-client-interface-pac\":{\"http-client-interface-configuration\":{\"application-name\":\"RegistryOffice\",\"release-number\":\"4.1.0\"}}}]}"
  }

> Priority:Low;

### PR DESCRIPTION
**Pull request by DanaSunal**
Fixes #801

### CODE REVIEW

**Review by MartinSunal — APPROVED** [review]

File: server/applicationPattern/applicationPattern/rest/client/RequestBuilder.js [hunk 1]
```diff
@@ -33,22 +34,13 @@ exports.BuildAndTriggerRestRequest = async function (operationClientUuid, method
             "body :" + JSON.stringify(requestBody) + "response code:" + response.status)
         return response;
     } catch (error) {
-        console.log(error);
         if (error.response) {
-            if (error.response.status) {
```
Comment (PrathibaJee) [inline server/applicationPattern/applicationPattern/rest/client/RequestBuilder.js:38]: This code we introduced to solve this problem https://github.com/openBackhaul/ApplicationPattern/issues/721.
Incase of ETIMEOUT/ECONNREFUSED , the service call is not reaching the destination and so the service record shall not be recorded to the EATL application from the server side. This is the reason for marking the status code for such cases to 404 and further we are recording the services to EATL from the client side. Kindly let me know whether this scenario shall also be take care.

**Review by PrathibaJee — CHANGES_REQUESTED** [review]

File: server/applicationPattern/applicationPattern/rest/client/RequestBuilder.js (hunk 1 above)
Comment (DanaSunal) [reply server/applicationPattern/applicationPattern/rest/client/RequestBuilder.js:38]: Yes, this scenario works as expected. Running RegistryOffice only, calling register-application results in:

```
POST /v1/register-application 204 587.549 ms - -
Request errored with Error: connect ECONNREFUSED 127.0.0.1:3002
Request errored with Error: connect ECONNREFUSED 127.0.0.1:3006
recordServiceRequestFromClient - record service request from client with body {"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1.1","user":"User Name","originator":"RegistryOffice","application-name":"TypeApprovalRegister","release-number":"2.0.1","operation-name":"/v1/regard-application","response-code":408} failed with response status: 408
recordServiceRequestFromClient - record service request from client with body {"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1.2","user":"User Name","originator":"RegistryOffice","application-name":"ApplicationLayerTopology","release-number":"2.0.1","operation-name":"/v1/update-ltp","response-code":408} failed with response status: 408
```

**Review by PrathibaJee — APPROVED** [review]
