### PR TITLE
issue-783 introduced eslint + husky + lint-staged and fixed major errors

### LINKED ISSUE #783: Introduce linter for improving code quality
The low hanging fruit for increasing code quality is to use linter (like https://eslint.org) in every application.

That gives us ability to:
- discover problems in code from static analysis
- keep the same standards in code
- having the same code formatting in every app

It can be also configured in a way that it will automatically run as pre-commit hook so it will force developers to keep the standards and it does not allow commit code which is not compliant.

We can start with most critical checks first and then include better standards as we go, e.g. we can start with eslint to check major problems (i.e. used but not defined variables), but not checking minor problems (i.e. unused variables).

Also, code formatting can be enabled later.

### PR DESCRIPTION
**Pull request by MartinSunal**
- eslint is used as a linter
- husky is configured as pre-commit hook which will trigger lint-staged in server/applicationPattern and server/basicServices
- lint-staged is configured to run eslint on staged files
- if eslint finds an error then commit is not created until it is not fixed
- all detected eslint errors are fixed except "no-async-promise-executor" which was disabled. At some point all code erroring on "no-async-promise-executor" should be fixed and the rule enabled.

Fixes #783

### CODE REVIEW

**Comment by MartinSunal** [comment]
example of steps how tooling was installed and configured:

1. modify `package.json` to contain:
```
  "scripts": {
    "prepare": "cd ../.. && husky install server/applicationPattern/.husky"
  },
  "devDependencies": {
    "eslint": "^8.44.0",
    "husky": "^8.0.0",
    "lint-staged": "^13.2.3"
  }
```
2. install dependencies by running `npm install` it will also create pre-commit hook in .git and it creates `.husky` folder
3. configure husky to execute lint-staged by running `npx husky add .husky/pre-commit "npx lint-staged"`
4. create `.eslintrc.json` file which contains configuration for eslint
5. create `.lintstagedrc.json` containing configuration for lint-staged

File: server/basicServices/basicServices/services/PrepareALTForwardingAutomation.js [hunk 1]
```diff
@@ -110,7 +110,7 @@ function getLTPForwardingAutomationInputListAsync(logicalTerminationPointconfigu
              * ServiceRequestCausesLtpUpdateRequest update-ltp
              ************************************************************************************/
             if (logicalTerminationPointconfigurationStatus) {
-                if (logicalTerminationPointconfigurationStatus.hasOwnProperty('httpClientConfigurationStatus')) {
+                if (Object.prototype.hasOwnProperty.call(logicalTerminationPointconfigurationStatus, 'httpClientConfigurationStatus')) {
```
Comment (DanaSunal) [inline server/basicServices/basicServices/services/PrepareALTForwardingAutomation.js:113]: using 'in' seems slightly less verbose and should be enough for this usage

File: server/applicationPattern/applicationPattern/onfModel/models/ProfileCollection.js [hunk 2]
```diff
@@ -11,6 +11,7 @@ const onfFormatter = require('../utility/OnfAttributeFormatter');
 const onfPaths = require('../constants/OnfPaths');
 const onfAttributes = require('../constants/OnfAttributes');
 const fileOperation = require('../../databaseDriver/JSONDriver');
+// eslint-disable-next-line no-unused-vars
```
Comment (DanaSunal) [inline server/applicationPattern/applicationPattern/onfModel/models/ProfileCollection.js:14]: why not delete the import?

**Review by DanaSunal — CHANGES_REQUESTED** [review]

File: server/applicationPattern/applicationPattern/onfModel/models/ProfileCollection.js (hunk 2 above)
Comment (MartinSunal) [reply server/applicationPattern/applicationPattern/onfModel/models/ProfileCollection.js:14]: it's used in jsdocs

File: server/basicServices/basicServices/services/PrepareALTForwardingAutomation.js (hunk 1 above)
Comment (MartinSunal) [reply server/basicServices/basicServices/services/PrepareALTForwardingAutomation.js]: I removed if statements completely because they are not needed there.

**Review by DanaSunal — DISMISSED** [review]

**Review by DanaSunal — APPROVED** [review]
